---
name: core
after:
  - framework/*,
  - cms/*
---
SiteTree:
  nested_urls: true
  create_default_pages: false
  extensions:
    - SiteTreeNavigation
SiteConfig:
  extensions:
    - SiteConfigDecorator
ErrorPage:
  extensions:
    - ErrorPageDecorator
RedirectorPage:
  extensions:
    - RedirectorPageDecorator
UserDefinedForm:
  extensions:
    - UserDefinedFormDecorator