---
name: 'core'
after:
  - 'framework/*',
  - 'cms/*'
---
SiteTree:
  nested_urls: true
  create_default_pages: false
SiteConfig:
  extensions:
    - 'SiteConfigDecorator'
ErrorPage:
  extensions:
    - 'ErrorPageDecorator'
UserDefinedForm:
  extensions:
    - 'UserDefinedFormDecorator'